name: face_recognition_companion
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: null
  date_range_picker: ^1.0.6
  dropdownfield: ^1.0.0
  firebase_auth: ^0.20.0
  firebase_core: ^0.7.0
  firebase_database: ^6.0.0
  flutter_sms: ^2.1.1
  flutter_spinkit: ^4.1.2
  flutter_windowmanager: ^0.0.2
  google_fonts: ^1.1.1
  hexcolor: ^1.0.6
  http: ^0.12.2
  intl: ^0.16.1
  logger: ^0.9.4
  provider: ^4.3.2+3
  qr_flutter: ^3.2.0
  rxdart: ^0.25.0
  shared_preferences: ^0.5.12+4
  splashscreen: ^1.3.5
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
